### ISSUE TITLE
ide internal errors in GoLand

### ISSUE THREAD

**Issue by peteyan** [zeromicro/goctl-intellij#33]
The Goctl plugin has encountered an exception without doing anything.
* Goctl version 1.1.9
* GoLand 2024.1.2
Build #GO-241.17011.92, built on May 23, 2024

The stacktrace.txt:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cn.xiaoheiban.action.ApiNewAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cn.xiaoheiban.go-zero]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

<img width="860" alt="image" src="https://github.com/zeromicro/goctl-intellij/assets/9857264/81e6b8fa-7274-4b2e-a9e3-3e4b0316d1d4">

**Comment by Xiphin** [comment]
临时解法，下载： [Goctl-1.1.11.zip](https://github.com/user-attachments/files/16850762/Goctl-1.1.11.zip) 通过加载本地插件的方式替换一下

**Comment by zzhaolei** [comment]
我也遇到这个问题了，每次打开 IDE 就弹出一个红框提示有错误。
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cn.xiaoheiban.action.ApiNewAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cn.xiaoheiban.go-zero]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by kesonan** [comment]
fixed #34
